# docker-compose.yml
version: '3.8'

services:
  web:
    build: 
      context: .
      target: development
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      NODE_ENV: development
      VITE_API_URL: http://localhost:3001
      DATABASE_URL: ${DATABASE_URL}
      LASTFM_USERNAME: ${LASTFM_USERNAME}
      LASTFM_API_KEY: ${LASTFM_API_KEY}
      WEBHOOK_AUTH_TOKEN: ${WEBHOOK_AUTH_TOKEN}
      DEFAULT_WEATHER: ${DEFAULT_WEATHER}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - .:/app
      - user_uploads:/public/assets/uploads
      - widget_data:/data
      - /app/node_modules
      - /app/admin/node_modules
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=website
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
    widget_data:
    user_uploads:
    pgdata: