version: '3.8'

services:
  web:
    build:
      context: .
      target: production
    ports:
      - "443:3000"
      - "80:3000"
    environment:
      NODE_ENV: production
      DATABASE_URL: ${DATABASE_URL}
      LASTFM_USERNAME: ${LASTFM_USERNAME}
      LASTFM_API_KEY: ${LASTFM_API_KEY}
      WEBHOOK_AUTH_TOKEN: ${WEBHOOK_AUTH_TOKEN}
      DEFAULT_WEATHER: ${DEFAULT_WEATHER}
      JWT_SECRET: ${JWT_SECRET}
    restart: unless-stopped
    volumes:
      - user_uploads:/public/assets/uploads
      - widget_data:/data
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: unless-stopped

volumes:
    user_uploads:
    widget_data:
    pgdata: